version: "3.7"

services:
  backend:
    container_name: delta-backend
    restart: always
    build: .
    env_file:
      - docker.env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: delta-mysql
    restart: always
    image: mysql:latest
    env_file:
      - docker.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default:
    external:
      name: delta